[GLUTEN-1925][CH] allow all parquet write jobs (especially for hive E…
oap-project/gluten pull request #1926
Opened 2023-06-13 02:47 UTC by binmahone

…TL jobs) to use native parquet writer

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2023-06-19 01:51 UTC, Yohahaha commented
Hi @binmahone , thanks for your great idea of this PR.

I would like implement ETL scenario too, but for Velox backend. I'm curious current status of this PR, could we talk more details in Slack?

2023-07-03 07:06 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/CHColumnToSparkRow.h
> +using MaskVector = std::unique_ptr<std::vector<size_t>>;
maybe renaming to MaskVectorPtr is better

2023-07-03 07:17 UTC, taiyang-li requested changes

2023-07-03 07:17 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/CHColumnToSparkRow.h
> +using MaskVector = std::unique_ptr<std::vector<size_t>>;
It is safer to use std::shared_ptr if you want to pass pointer all around

2023-07-03 07:17 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
> +        size_t row_idx = masks == nullptr ? i : masks->at(i);
This may slow down for loop performance because of extra if-elses for fixed-length data types, better to add another function with masks

2023-07-03 07:17 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
> +        for (size_t i = 0; i < num_rows ; i++)
pls apply clang-format

2023-07-03 07:17 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.h
> +    int64_t originalBlockAddress;
pls follow CH's code style: originalBlockAddress -> original_block_address,  int64_t -> Int64

2023-07-03 09:22 UTC, taiyang-li requested changes

2023-07-04 10:42 UTC, closed without merging