[GLUTEN-1950][CH]support asof join fallback for clickhouse backend
oap-project/gluten pull request #1953
Opened 2023-06-14 08:37 UTC by taiyang-li

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#1950)

2023-06-14 08:44 UTC, zzcclp commented
please add some case

2023-06-16 09:31 UTC, taiyang-li commented
Must wait until CH backend supporting ASOF JOIN, which is doing by @shuai-xu .

2023-06-19 03:58 UTC, zheniantoushipashi requested changes

2023-06-19 03:58 UTC, zheniantoushipashi commented on backends-clickhouse/src/main/scala/io/glutenproject/utils/CHJoinValidateUtil.scala
> +        if (leftFallback || rightFallback || leftInequalities + rightInequalities > 1) {
select  * from l  left join  r  on  l.a = r.a and (r.a > 1 or r.b < 10)

对于这种用 or 连接的不等式，  backend 是支持的， 

select * from l  left join r  on  l.a = r.a AND (r.a != 1)

这种非两边都有  join keys 的不等式 ch 也是支持的

2023-06-19 03:58 UTC, zheniantoushipashi commented on backends-clickhouse/src/main/scala/io/glutenproject/utils/CHJoinValidateUtil.scala
> +  // 1. Only one inequality condition is allowed in clickhouse asof join, e.g. <, <=, >, >=
这里最好可以举一些例子说明下，不然这里的逻辑让人很难短时间搞明白， 
把不同的分支情况，举例子说明下

2023-06-19 09:57 UTC, taiyang-li commented on backends-clickhouse/src/main/scala/io/glutenproject/utils/CHJoinValidateUtil.scala
> +        if (leftFallback || rightFallback || leftInequalities + rightInequalities > 1) {
好的。我再看看

2023-06-20 06:33 UTC, closed without merging