[GlUTEN-2018][GlUTEN-2027][GLUTEN-1939][CH] Fix error field value behavior
oap-project/gluten pull request #2044
Opened 2023-06-21 10:06 UTC by loneylee

…avior

## What changes were proposed in this pull request?

* 和Spark对齐字段列异常时的行为
* 修复2023-02-29被读出为03-01的bug
* 和Spark对齐字段前后是否需要去空格的行为

2023-06-26 02:30 UTC, taiyang-li requested changes

2023-06-26 07:40 UTC, loneylee commented on cpp-ch/local-engine/Storages/Serializations/ExcelDecimalReader.h
> +void deserializeDecimalTextCSV(IColumn & column, ReadBuffer & istr, UInt32 precision, UInt32 scale, const FormatSettings & formatSettings)
fix

2023-06-26 07:40 UTC, loneylee commented on cpp-ch/local-engine/Storages/Serializations/ExcelSerialization.h
> -    explicit ExcelSerialization(const SerializationPtr & nested_, String & escape_) : nested_ptr(nested_), escape(escape_){};
fix

2023-06-26 07:40 UTC, loneylee commented on cpp-ch/local-engine/Storages/Serializations/ExcelDecimalReader.h
> +inline bool readGlutenCSVDecimalText(ReadBuffer & buf, T & x, uint32_t precision, uint32_t & scale, const FormatSettings & format_settings)
fix

2023-06-26 07:40 UTC, loneylee commented on cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.cpp
> +bool readGlutenDateText(LocalDate & date, DB::ReadBuffer & buf, const DB::FormatSettings & settings)
fix

2023-06-26 07:41 UTC, loneylee commented on cpp-ch/local-engine/Storages/Serializations/ExcelDecimalSerialization.h
> +    void serializeTextEscaped(const IColumn & column, size_t row_num, WriteBuffer & ostr, const FormatSettings &) const override{};
fix

2023-06-26 07:41 UTC, loneylee commented on cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.h
> +inline bool check_date(const UInt16 & year, const UInt8 & month_, const UInt8 & day_)
fix

2023-06-26 09:42 UTC, loneylee commented
Run Gluten Clickhouse CI

2023-06-27 03:18 UTC, taiyang-li commented
LGTM

2023-06-27 07:28 UTC, baibaichen approved these changes
LGTM

2023-06-27 07:28 UTC, merged