[GLUTEN-2193][CH] Support array_position and fix array_contains
oap-project/gluten pull request #2296
Opened 2023-07-11 06:49 UTC by exmy

## What changes were proposed in this pull request?

## How was this patch tested?

UT

2023-07-14 07:07 UTC, taiyang-li requested changes

2023-07-14 07:07 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayContains.cpp
> +        return toFunctionNode(actions_dag, "if", {or_node, null_const_node, nested_multi_if_node});
这里是否可以将所有分支展开，有利于multiIf内部的一些短路优化. 
multiIf(arr = null, null, val = null, null, has(assumeNotNull(arr), val), true, has(assumeNotNull(arr), null), null, false)

2023-07-14 07:07 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayPosition.cpp
> +            throw Exception(ErrorCodes::BAD_ARGUMENTS, "Function {} requires exactly two arguments", getName());
NUMBER_OF_ARGUMENTS_DOESNT_MATCH

2023-07-14 07:07 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayPosition.cpp
> +        if (!is_arr_nullable && !is_value_nullable)
没必要单独拿出来处理，统一走indexOf(assertNotNull(arr), value)就行了，不管arr是nullable的还是非nullable

2023-07-14 10:39 UTC, exmy commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayContains.cpp
> +        if (!is_arr_nullable && !is_value_nullable && !is_arr_elem_nullable)
分开比较好处理返回 Nullable 和非 Nullable 的情况，如果去掉这个有个 Spark 的 UT 会失败

2023-07-17 04:18 UTC, taiyang-li requested changes

2023-07-17 04:18 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayPosition.cpp
> +                indexOf(assertNotNull(arr), value)
assertNotNull -> assumeNotNull

2023-07-17 04:18 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayPosition.cpp
> +        DataTypePtr wrap_arr_nullable_type = wrapNullableType(true, ch_function_node->result_type);
这里其实没必要wrap nullable的，因为最后convertNodeTypeIfNeeded会兜底.

2023-07-17 07:06 UTC, taiyang-li approved these changes
LGTM

2023-07-17 09:59 UTC, liuneng1994 approved these changes
LGTM

2023-07-17 10:01 UTC, zzcclp approved these changes
LGTM

2023-07-17 10:01 UTC, merged