[CH] support months_between function
oap-project/gluten pull request #2388
Opened 2023-07-19 03:23 UTC by zhanglistar

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#2348)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
UT

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2023-07-19 04:06 UTC, taiyang-li requested changes

2023-07-19 04:06 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/months_between.cpp
> +        return toFunctionNode(actions_dag, "if", {round_arg, round_node, devide_node});
return加一个convertNodeTypeIfNeeded，避免输出类型与substrait function的output_type不一致

2023-07-19 04:06 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/months_between.cpp
> +        return toFunctionNode(actions_dag, "if", {round_arg, round_node, devide_node});
参考cpp-ch/local-engine/Parser/example_udf/myMd5.cpp

2023-07-19 04:06 UTC, taiyang-li commented on gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
> +    // val lowerFormatNode = ExpressionBuilder.makeStringLiteral("day")
remove useless codes

2023-07-19 04:06 UTC, taiyang-li commented on backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDatetimeExpressionSuite.scala
> +  test("test months_between function") {
months_between有没有spark官方的ut, 可以在ClickhouseTestSettings里开启。

2023-07-19 09:39 UTC, zhanglistar commented on backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDatetimeExpressionSuite.scala
> +  test("test months_between function") {
现在有精度问题， 还需要进一步缩小精度。spark是到微妙，但是ch只有到秒。

2023-07-19 09:41 UTC, zhanglistar commented
Now we have precision problem, spark support micro seconds but ch only seconds. Need to work.

2023-07-27 08:40 UTC, zzcclp approved these changes
LGTM

2023-07-27 10:31 UTC, liuneng1994 approved these changes
LGTM

2023-07-27 11:57 UTC, merged