[GLUTEN-2456][CH] Support push down filter in parquet input format reader
oap-project/gluten pull request #2457
Opened 2023-07-25 02:22 UTC by KevinyhZou

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#2456)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2023-07-25 03:12 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
> +// clang-format off
No need to set clang-format off for includes. Make sure clang-format formats all codes.

2023-07-25 03:16 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
> +    bool checkRowGroupIfRequired(std::unique_ptr<parquet::RowGroupMetaData> meta)
函数定义放在cpp文件里

2023-07-25 03:21 UTC, taiyang-li requested changes

2023-07-25 03:21 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
> +        auto setColumnRangeAndType = [&](DB::Range range, DB::DataTypePtr type, std::vector<DB::Range> & ranges, DB::DataTypes & types) -> void
follow code style of CH, setColumnRangeAndType -> set_column_range_and_type

2023-07-25 03:21 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
> +        };
proper blank line

2023-07-25 03:21 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
> +    void setFilters(std::vector<DB::KeyCondition> & filters_)
输入参数加const

2023-07-25 03:21 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
> +            filters.push_back(filters_[i]);
std::vector赋值直接用 filters = filters_;

2023-07-25 03:21 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
> +// clang-format on
除非特殊需要，最好不要随意开闭clang-format

2023-07-25 03:31 UTC, taiyang-li requested changes

2023-07-25 03:31 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> +    // auto source_step = std::make_unique<ReadFromStorageStep>(std::move(source_pipe), "substrait local files", nullptr);
remove useless codes

2023-07-25 03:31 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
> +#include <memory>
重复include, 建议打开clang-format, 格式化下所有#include

2023-07-25 03:31 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
> -
代码段之间适当保留的空行，这里没必要去掉。

2023-07-25 03:48 UTC, taiyang-li requested changes

2023-07-25 03:48 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
> +            setColumnMaxMinAndType(column_chunk_meta->statistics(), column_chunk_meta->type(), column_type_length, column_max_mins, column_types);
从设计上来讲，这里最好不要将std::vector::push_back的逻辑和setColumnMaxMinAndType耦合，setColumnMaxMinAndType只返回DB::Range，再在setColumnMaxMinAndType外面将DB::Range追加到std::vector<DB::Range>中。方便后续扩展。

2023-08-01 07:28 UTC, taiyang-li requested changes

2023-08-01 07:28 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
> +    virtual String getFileFormat() const { return "unknown"; }
这是必须由派生类实现的接口，定义为纯虚函数较妥

2023-08-01 07:28 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
> +#    include <utility>
![image](https://github.com/oap-project/gluten/assets/8181003/036f980b-4e30-4de5-9ef5-471552e3272c)

删掉中间空行，使用clang-format重新格式化，它会自动去重。

2023-08-01 07:40 UTC, taiyang-li requested changes

2023-08-01 07:40 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
> +                ranges.push_back(range);
ranges.emplace_back(std::move(range));

2023-08-01 07:40 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.cpp
> +    if (filter_column_keys.size() != 0)
if (!filter_column_keys.empty())

2023-08-01 07:40 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
> +    for (size_t i=0; i < files.size(); ++i)
格式化

2023-08-03 01:31 UTC, KevinyhZou commented
Fixed done, pelase review the code again @taiyang-li

2023-08-03 01:51 UTC, taiyang-li approved these changes
LGTM

2023-08-14 07:36 UTC, baibaichen approved these changes
LGTM

2023-08-14 09:51 UTC, taiyang-li approved these changes
LGTM

2023-08-15 07:15 UTC, baibaichen approved these changes
LGTM

2023-08-15 07:15 UTC, merged