[GLUTEN-2582][CH]Bug fix crash problem in array<struct> filter
oap-project/gluten pull request #2606
Opened 2023-08-04 02:52 UTC by KevinyhZou

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#2582)

## How was this patch tested?
UT

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2023-08-08 06:27 UTC, taiyang-li requested changes

2023-08-08 06:27 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayElement.cpp
> +class FunctionParserElementAt : public FunctionParserArrayElement
最好能每个scalar function对应一个文件。
另外需要将SCALAR_FUNCTION中对应的kv entry删掉。

2023-08-08 07:24 UTC, lgbo-ustc commented on cpp-ch/local-engine/Parser/TypeParser.cpp
> +
There are space here?

2023-08-08 08:13 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayElement.cpp
> +class FunctionParserElementAt : public FunctionParserArrayElement
趁此机会将涉及到的几个function的spark ut开启，看看能否pass

2023-08-08 10:36 UTC, KevinyhZou commented on cpp-ch/local-engine/Parser/TypeParser.cpp
> +
fixed done.

2023-08-08 10:36 UTC, KevinyhZou commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayElement.cpp
> +class FunctionParserElementAt : public FunctionParserArrayElement
arrayElement 相关的function 目前主要包括：get_array_item, element_at, get_map_value，目前都已经添加到UT中了。

2023-08-08 14:13 UTC, taiyang-li requested changes

2023-08-08 14:13 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/arrayElement.h
> +    {
最好能添加一些注释，说明最终返回的function node是如何组成的，可参考其他function parser

2023-08-10 05:40 UTC, baibaichen commented
@KevinyhZou you need update clickhouse.version, the commit id is  `461c7a0bf12`

2023-08-10 09:53 UTC, baibaichen approved these changes
LGTM

2023-08-10 09:53 UTC, merged