[GLUTEN-2164][CH] Support function concat_ws
oap-project/gluten pull request #2608
Opened 2023-08-04 03:03 UTC by exmy

## What changes were proposed in this pull request?

## How was this patch tested?

UT

2023-08-04 03:53 UTC, taiyang-li requested changes

2023-08-04 03:53 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/concat_ws.cpp
> +/*
follow current naming rules: concat_ws.cpp -> concatWs.cpp

2023-08-07 02:35 UTC, taiyang-li approved these changes
LGTM

2023-08-08 03:11 UTC, liuneng1994 approved these changes
LGTM

2023-08-08 03:11 UTC, merged