[GLUTEN-3072][CH] Optimization for `get_json_object`
oap-project/gluten pull request #3111
Opened 2023-09-12 02:05 UTC by lgbo-ustc

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

Fixes: #3072

- reduce the memory consumption
- improve the speed

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

unit tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2023-09-12 02:37 UTC, lgbo-ustc commented
test result.

| repeated functions   | before | after |
| -------- | ------- | ------- |
|7  | 27s   | 17s|
|2 | 9.4s     | 8.9s |
| 1    | 6.6s |  6.7s   |

2023-09-12 04:08 UTC, taiyang-li requested changes

2023-09-12 04:08 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
> +    if (format_settings.orc.use_fast_decoder)
format factory中已经包含了根据开关选择的逻辑，是否可通过FormatFactory::getInput 接口复用

2023-09-12 04:09 UTC, lgbo-ustc commented on cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
> +    if (format_settings.orc.use_fast_decoder)
有问题。无法使用factory的接口

2023-09-12 04:11 UTC, lgbo-ustc commented on cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
> +    if (format_settings.orc.use_fast_decoder)
先去掉这个带动了，这个PR对内存的需求已经变小了

2023-09-12 08:54 UTC, lwz9103 commented
Run Gluten Clickhouse CI

2023-09-13 10:31 UTC, liuneng1994 approved these changes
LGTM

2023-09-14 02:32 UTC, merged