[GLUTEN-3221][CH]fix readDecimal func for r2c when reading negative decimal data
oap-project/gluten pull request #3222
Opened 2023-09-20 11:15 UTC by lhuang09287750

## What changes were proposed in this pull request?

pad buffer with '\xff' other than 0 when reading negative decimal data during r2c

(Fixes: \#3221)

## How was this patch tested?

add a new test case in GlutenDataFrameAggregateSuite

2023-09-21 02:33 UTC, lhuang09287750 commented
retest this please

2023-09-21 06:55 UTC, taiyang-li requested changes

2023-09-21 06:55 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/SparkRowToCHColumn.cpp
> +    char * tmp_buf = new char[length];
you forgot to freee it .

2023-09-21 07:04 UTC, taiyang-li requested changes

2023-09-21 07:04 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/SparkRowToCHColumn.cpp
> +    char * tmp_buf = new char[length];
这里又增加了一个buffer的创建、复制、销毁，外加一个String的构造、swap和销毁，开销不小，可能会影响性能。是否可以在不创建额外buffer的情况下，确定对应的decimal value是否为negative ?

2023-09-21 07:43 UTC, lhuang09287750 commented
@taiyang-li 收到，我试试不用buffer来判断负的decimal

2023-09-21 08:38 UTC, lhuang09287750 commented
@taiyang-li 改了判断方法，因为decimal value存的是对应的整型的补码，直接用其包含最高位（符号位）的那个字节转成int8来判断 整体decimal的正负。

2023-09-22 07:29 UTC, taiyang-li approved these changes
LGTM

2023-09-25 02:24 UTC, taiyang-li approved these changes

2023-10-26 07:08 UTC, lhuang09287750 commented
fixed in my anthor pr,close!

2023-10-26 07:08 UTC, closed without merging