[CH] Remove ENABLE_LOCAL_FORMATS
oap-project/gluten pull request #3409
Opened 2023-10-15 06:42 UTC by baibaichen

We intrduced ENABLE_LOCAL_FORMATS in https://github.com/oap-project/gluten/pull/1390, which make us cann't test our own parquet formt(defined in local engine) easily. This PR remove it and using runtime config instead of it.

1. For PARQUET, using Runtime Config(`spark.gluten.sql.columnar.backend.ch.runtime_config.enable_local_parquet_format`) instead of it, upgrade ch_parquet to latest arrow.
2. For ORC, only use clickhouse format

Also, I Sync clang format from clickhouse, and update  IndentPPDirectives to None for better style

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#3408)

## How was this patch tested?

using exited UT.

2023-10-16 02:20 UTC, taiyang-li requested changes

2023-10-16 02:20 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
> +        bool useLocalFormat = context->getConfigRef().getBool("enable_local_parquet_format", false);
use_local_format

2023-10-16 02:20 UTC, taiyang-li commented on cpp-ch/local-engine/Storages/ch_parquet/CMakeLists.txt
> +    -Wno-tautological-unsigned-zero-compare
加它是什么目的

2023-10-16 02:20 UTC, taiyang-li commented on backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
> +      .set(
是否可同时覆盖开关的两个值。

2023-10-16 06:00 UTC, baibaichen commented on cpp-ch/local-engine/Storages/ch_parquet/CMakeLists.txt
> +    -Wno-tautological-unsigned-zero-compare
see `cpp-ch/local-engine/Storages/ch_parquet/arrow/encoding.cc#2888`, don't know why arrow try to test `unsigned int` is negitive or not

``` c++
uint32_t num_bytes = ..;
 // this is why need -Wno-tautological-unsigned-zero-compare 
 if (num_bytes < 0 || ...) {
  ..
 }
```

2023-10-16 06:02 UTC, baibaichen commented on backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
> +      .set(
All testcases use the same Parquet files, and only AQE test using local format.

2023-10-16 06:25 UTC, taiyang-li approved these changes
LGTM

2023-10-16 11:09 UTC, zzcclp approved these changes
LGTM

2023-10-16 11:30 UTC, merged

2023-10-17 03:17 UTC, baibaichen commented
name | arrow(ms) | use_local_format(ms)| use_local_format-arrow
-- | -- | -- | --
q01 | 3849 | 3716 | -133
q02 | 3484 | 3186 | -298
q03 | 6031 | 5632 | -399
q04 | 3711 | 3557 | -154
q05 | 9845 | 9240 | -605
q06 | 1093 | 1268 | 175
q07 | 10854 | 10684 | -170
q08 | 4560 | 4672 | 112
q09 | 9228 | 9264 | 36
q10 | 6750 | 5917 | -833
q11 | 1852 | 1949 | 97
q12 | 4236 | 4062 | -174
q13 | 5043 | 3857 | -1186
q14 | 2097 | 2248 | 151
q15 | 3993 | 4198 | 205
q16 | 6168 | 6047 | -121
q17 | 10844 | 10909 | 65
q18 | 19723 | 18820 | -903
q19 | 3979 | 3594 | -385
q20 | 3292 | 3331 | 39
q22 | 1193 | 1154 | -39