[GLUTEN-3412][CH]Bug fix element_at 1st element is map type
oap-project/gluten pull request #3413
Opened 2023-10-16 05:16 UTC by KevinyhZou

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#3412)

## How was this patch tested?

TEST BY UT

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

2023-10-16 06:09 UTC, taiyang-li requested changes

2023-10-16 06:09 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/elementAt.cpp
> +            const DataTypeMap * map_type = checkAndGetDataType<DataTypeMap>(removeNullable(parsed_args[0]->result_type).get());
use isMap,

2023-10-16 06:25 UTC, KevinyhZou commented on cpp-ch/local-engine/Parser/scalar_function_parser/elementAt.cpp
> +            const DataTypeMap * map_type = checkAndGetDataType<DataTypeMap>(removeNullable(parsed_args[0]->result_type).get());
done

2023-10-24 14:32 UTC, binmahone approved these changes

2023-10-24 14:32 UTC, merged