[GLUTEN-3521][CH]Fix substring start index must start from 1
oap-project/gluten pull request #3524
Opened 2023-10-25 03:08 UTC by KevinyhZou

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#3521)

## How was this patch tested?

TEST BY UT

2023-10-25 12:28 UTC, taiyang-li requested changes

2023-10-25 12:28 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
> +        if (!DB::WhichDataType(start_index_data_type).isInt())
use isInteger make is simpler.

2023-10-25 12:28 UTC, taiyang-li commented on cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
> +            return toFunctionNode(actions_dag, "substringUTF8", {parsed_args[0], if_node, parsed_args[2]});
wrap convertNodeTypeIfNeeded

2023-10-26 02:09 UTC, KevinyhZou commented on cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
> +        if (!DB::WhichDataType(start_index_data_type).isInt())
done

2023-10-26 02:09 UTC, KevinyhZou commented on cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
> +            return toFunctionNode(actions_dag, "substringUTF8", {parsed_args[0], if_node, parsed_args[2]});
done

2023-11-06 13:26 UTC, binmahone approved these changes

2023-11-06 13:26 UTC, merged