[GLUTEN-3666][VL] Refine connector IO executor initialization
oap-project/gluten pull request #3696
Opened 2023-11-13 09:27 UTC by Yohahaha

Change default value of spark.gluten.sql.columnar.backend.velox.SplitPreloadPerDriver to 0, make startup message more clear.

(Fixes: \#3666)

2023-11-14 02:46 UTC, Yohahaha commented
@zhli1142015 @zhouyuan please help review this, thank you!

2023-11-14 03:50 UTC, zhztheplayer commented
> Change default value of spark.gluten.sql.columnar.backend.velox.SplitPreloadPerDriver to 0, make startup message more clear.

Would you like to share the reason of doing this? Thanks!

2023-11-14 03:58 UTC, zhztheplayer approved these changes

2023-11-14 04:27 UTC, Yohahaha commented
> > Change default value of spark.gluten.sql.columnar.backend.velox.SplitPreloadPerDriver to 0
> 
> Would you like to share the reason of doing this? Thanks!

preload split does not fit Gluten's design perfectly, disable it by default avoid unexpected behavior.

2023-11-14 05:11 UTC, zhztheplayer requested changes
> preload split does not fit Gluten's design perfectly, disable it by default avoid unexpected behavior.

Can you elaborate? Like it may lead memory issue or something?

2023-11-14 06:09 UTC, Yohahaha commented
> > preload split does not fit Gluten's design perfectly, disable it by default avoid unexpected behavior.
> 
> Can you elaborate? Like it may lead to memory issue or something?

Gluten use single thread execution mode and suppose all Velox object should be released when Spark task is finished, but the thread which preload split will run out live of Velox Task and it may access dangling pointer.
https://github.com/facebookincubator/velox/issues/6994
https://github.com/prestodb/presto/issues/20020

2023-11-15 01:51 UTC, Yohahaha commented
> Hi @Yohahaha yes, hongze is working on this, the split preload feature will be fixed by this: #3419

I think current patch does not change functionality.

2024-02-19 02:15 UTC, closed without merging